# Generated by Django 4.0.2 on 2022-05-06 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default='')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=100)),
                ('projectDescription', models.CharField(max_length=300)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issueId', models.AutoField(primary_key=True, serialize=False)),
                ('issueName', models.CharField(max_length=100)),
                ('issueType', models.CharField(max_length=100)),
                ('reporterId', models.IntegerField()),
                ('issueStatus', models.IntegerField()),
                ('issueDescription', models.CharField(max_length=300)),
                ('assigneeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.project')),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30, null=True)),
                ('text', models.CharField(max_length=200, null=True)),
                ('createdOn', models.DateTimeField(null=True)),
                ('updatedOn', models.DateTimeField(null=True)),
                ('authorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
                ('issueId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.issue')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
